version: "1.0"
info:
  model: int-scaffold
packages:
- name: Man_LD_Aug01Project
  gitServerName: Lakshmi
  gitUrl: https://github.com/lakshmidevi277/Man_LD_Aug01Project
  gitUsername: lakshmidevi277
  gitBranch: main
- name: MarketoTest1011
  gitServerName: Karthik
  gitUrl: https://github.com/karthikbm
  gitUsername: karthikbm
  gitBranch: main
- name: CommonUtilities
  gitServerName: asam22
  gitUrl: https://github.webmethods.io/ades
  gitUsername: asam
  gitBranch: main
